#ifndef __EC11_HANDLE_H
#define __EC11_HANDLE_H
#include <stdint.h>
#include <stdbool.h>

#include "EncoderEC11.h"

#define EC11_TASK_TIME          1


typedef enum
{
	VOLTAGE_ONE_ADD,
	VOLTAGE_TEN_ADD,
	VOLTAGE_HUNDRED_ADD,
	VOLTAGE_THOUSAND_ADD,
	VOLTAGE_ONE_REDUCE,
	VOLTAGE_TEN_REDUCE,
	VOLTAGE_HUNDRED_REDUCE,
	VOLTAGE_THOUSAND_REDUCE,
	
	VOLTAGE_POSITION,
	VOL_EC11_END_EVENT,

}vol_ec11_event_e;

typedef enum
{
	CURRENT_ONE_ADD,
	CURRENT_TEN_ADD,
	CURRENT_HUNDRED_ADD,
	CURRENT_THOUSAND_ADD,
	CURRENT_ONE_REDUCE,
	CURRENT_TEN_REDUCE,
	CURRENT_HUNDRED_REDUCE,
	CURRENT_THOUSAND_REDUCE,
	
	CURRENT_POSITION,
	CUR_EC11_END_EVENT,

}cur_ec11_event_e;




void ec11_handle(void);

#endif // __ENCODER_EC11_H

