#ifndef __OUTPUT_H
#define __OUTPUT_H
#include "flash.h"
#define FLASH_TASK_TIME            5
#define DATA_SIZE                  2
#define FLASH_MENBER               20



/* a area data address */
/* handle data */
#define A_VOLTAGE_SET_DATA_ADDRESS       (0x08000000 + 1024 * 254)
#define A_CURRENT_SET_DATA_ADDRESS       A_VOLTAGE_SET_DATA_ADDRESS + DATA_SIZE   

#define A_MOD1_VOLTAGE_SET_DATA_ADDRESS  A_CURRENT_SET_DATA_ADDRESS + DATA_SIZE   
#define A_MOD1_CURRENT_SET_DATA_ADDRESS  A_MOD1_VOLTAGE_SET_DATA_ADDRESS + DATA_SIZE   
#define A_MOD1_OCP_MODE_ADDRESS          A_MOD1_CURRENT_SET_DATA_ADDRESS + DATA_SIZE   

#define A_MOD2_VOLTAGE_SET_DATA_ADDRESS  A_MOD1_OCP_MODE_ADDRESS + DATA_SIZE   
#define A_MOD2_CURRENT_SET_DATA_ADDRESS  A_MOD2_VOLTAGE_SET_DATA_ADDRESS + DATA_SIZE  
#define A_MOD2_OCP_MODE_ADDRESS          A_MOD2_CURRENT_SET_DATA_ADDRESS + DATA_SIZE 

#define A_MOD3_VOLTAGE_SET_DATA_ADDRESS  A_MOD2_OCP_MODE_ADDRESS + DATA_SIZE   
#define A_MOD3_CURRENT_SET_DATA_ADDRESS  A_MOD3_VOLTAGE_SET_DATA_ADDRESS + DATA_SIZE  
#define A_MOD3_OCP_MODE_ADDRESS          A_MOD3_CURRENT_SET_DATA_ADDRESS + DATA_SIZE 

#define A_MOD4_VOLTAGE_SET_DATA_ADDRESS  A_MOD3_OCP_MODE_ADDRESS + DATA_SIZE   
#define A_MOD4_CURRENT_SET_DATA_ADDRESS  A_MOD4_VOLTAGE_SET_DATA_ADDRESS + DATA_SIZE  
#define A_MOD4_OCP_MODE_ADDRESS          A_MOD4_CURRENT_SET_DATA_ADDRESS + DATA_SIZE 

#define A_OCP_MODE_ADDRESS               A_MOD4_OCP_MODE_ADDRESS + DATA_SIZE
#define A_VOLTAGE_LIMIN_STATE_ADDRESS    A_OCP_MODE_ADDRESS + DATA_SIZE
#define A_CURRENT_LIMIN_STATE_ADDRESS    A_VOLTAGE_LIMIN_STATE_ADDRESS + DATA_SIZE
#define A_LOCK_STATE_ADDRESS             A_CURRENT_LIMIN_STATE_ADDRESS + DATA_SIZE
#define A_SPEAK_STATE_ADDRESS            A_LOCK_STATE_ADDRESS + DATA_SIZE
#define A_FLASH_VERSION_ADDRESS          A_SPEAK_STATE_ADDRESS + DATA_SIZE                         

/* b area data address */
/* handle data */
#define B_VOLTAGE_SET_DATA_ADDRESS       (0x08000000 + 1024 * 255)
#define B_CURRENT_SET_DATA_ADDRESS       B_VOLTAGE_SET_DATA_ADDRESS + DATA_SIZE   

#define B_MOD1_VOLTAGE_SET_DATA_ADDRESS  B_CURRENT_SET_DATA_ADDRESS + DATA_SIZE   
#define B_MOD1_CURRENT_SET_DATA_ADDRESS  B_MOD1_VOLTAGE_SET_DATA_ADDRESS + DATA_SIZE   
#define B_MOD1_OCP_MODE_ADDRESS          B_MOD1_CURRENT_SET_DATA_ADDRESS + DATA_SIZE   

#define B_MOD2_VOLTAGE_SET_DATA_ADDRESS  B_MOD1_OCP_MODE_ADDRESS + DATA_SIZE   
#define B_MOD2_CURRENT_SET_DATA_ADDRESS  B_MOD2_VOLTAGE_SET_DATA_ADDRESS + DATA_SIZE  
#define B_MOD2_OCP_MODE_ADDRESS          B_MOD2_CURRENT_SET_DATA_ADDRESS + DATA_SIZE 

#define B_MOD3_VOLTAGE_SET_DATA_ADDRESS  B_MOD2_OCP_MODE_ADDRESS + DATA_SIZE   
#define B_MOD3_CURRENT_SET_DATA_ADDRESS  B_MOD3_VOLTAGE_SET_DATA_ADDRESS + DATA_SIZE  
#define B_MOD3_OCP_MODE_ADDRESS          B_MOD3_CURRENT_SET_DATA_ADDRESS + DATA_SIZE 

#define B_MOD4_VOLTAGE_SET_DATA_ADDRESS  B_MOD3_OCP_MODE_ADDRESS + DATA_SIZE   
#define B_MOD4_CURRENT_SET_DATA_ADDRESS  B_MOD4_VOLTAGE_SET_DATA_ADDRESS + DATA_SIZE  
#define B_MOD4_OCP_MODE_ADDRESS          B_MOD4_CURRENT_SET_DATA_ADDRESS + DATA_SIZE 

#define B_OCP_MODE_ADDRESS               B_MOD4_OCP_MODE_ADDRESS + DATA_SIZE
#define B_VOLTAGE_LIMIN_STATE_ADDRESS    B_OCP_MODE_ADDRESS + DATA_SIZE
#define B_CURRENT_LIMIN_STATE_ADDRESS    B_VOLTAGE_LIMIN_STATE_ADDRESS + DATA_SIZE
#define B_LOCK_STATE_ADDRESS             B_CURRENT_LIMIN_STATE_ADDRESS + DATA_SIZE
#define B_SPEAK_STATE_ADDRESS            B_LOCK_STATE_ADDRESS + DATA_SIZE

#define B_FLASH_VERSION_ADDRESS          B_SPEAK_STATE_ADDRESS + DATA_SIZE  

typedef enum
{
    FLASH_START = 0,
    FLASH_HANDLE_DATA,
    FLASH_GENERAL_DATA,
    FLASH_FINSH,
} flash_state_t;


typedef struct
{
    flash_state_t state;
} flash_handle_t;

void flash_handle(void);

#endif
